
import path from "path";
import { mkdir } from "fs/promises";
import ExcelJS from "exceljs";
import { VillaQtoBoqSection } from "./villaQtoEngine";

const BRAND_COLOR = "1E3A5F";
const HEADER_BG = "1E3A5F";
const HEADER_FONT_COLOR = "FFFFFF";
const SECTION_BG = "E8F0FE";
const SUBTOTAL_BG = "F0F4F8";
const VERIFY_BG = "FEF3C7";

export async function generateV15ExcelBOQ(data: {
  projectName: string;
  sections: VillaQtoBoqSection[];
  outputDir: string;
  revision?: number;
  projectType?: string;
  trustGate?: string;
  auditData?: any;
}): Promise<string> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "QS-HUB V15";
  workbook.created = new Date();

  const sheet = workbook.addWorksheet("Bill of Quantities", {
    properties: { defaultColWidth: 15 },
    pageSetup: {
      paperSize: 9, // A4
      orientation: "landscape",
      fitToPage: true,
      fitToWidth: 1,
      fitToHeight: 0,
    },
  });

  // ── Title row ──
  const titleRow = sheet.addRow([`BILL OF QUANTITIES — ${data.projectName}`]);
  titleRow.font = { bold: true, size: 14, color: { argb: BRAND_COLOR } };
  sheet.mergeCells(titleRow.number, 1, titleRow.number, 6);
  titleRow.alignment = { horizontal: "center" };

  // ── Meta row ──
  const metaParts = [
    data.projectType ? `Type: ${data.projectType.toUpperCase()}` : '',
    data.revision ? `Rev ${data.revision}` : '',
    data.trustGate ? `Gate: ${data.trustGate}` : '',
    `Date: ${new Date().toLocaleDateString('en-GB')}`,
  ].filter(Boolean);
  const metaRow = sheet.addRow([metaParts.join(' | ')]);
  metaRow.font = { size: 9, color: { argb: "666666" } };
  sheet.mergeCells(metaRow.number, 1, metaRow.number, 6);
  metaRow.alignment = { horizontal: "center" };
  sheet.addRow([]); // spacer

  // ── Column headers ──
  sheet.columns = [
    { header: "S.No", key: "sn", width: 8 },
    { header: "Description", key: "desc", width: 55 },
    { header: "Unit", key: "unit", width: 10 },
    { header: "Quantity", key: "qty", width: 15 },
    { header: "Rate (AED)", key: "rate", width: 15 },
    { header: "Amount (AED)", key: "amount", width: 18 },
  ];

  const headerRow = sheet.getRow(4);
  headerRow.values = ["S.No", "Description", "Unit", "Quantity", "Rate (AED)", "Amount (AED)"];
  headerRow.font = { bold: true, color: { argb: HEADER_FONT_COLOR }, size: 11 };
  headerRow.fill = { type: "pattern", pattern: "solid", fgColor: { argb: HEADER_BG } };
  headerRow.alignment = { horizontal: "center", vertical: "middle" };
  headerRow.height = 28;
  headerRow.eachCell((cell) => {
    cell.border = {
      bottom: { style: "medium", color: { argb: BRAND_COLOR } },
    };
  });

  let grandTotal = 0;
  let globalItemNo = 1;

  data.sections.forEach((section) => {
    // Section header row
    const sectionRow = sheet.addRow({ desc: section.sectionName });
    sectionRow.font = { bold: true, size: 11, color: { argb: BRAND_COLOR } };
    sectionRow.fill = { type: "pattern", pattern: "solid", fgColor: { argb: SECTION_BG } };
    sheet.mergeCells(sectionRow.number, 1, sectionRow.number, 6);

    section.items.forEach((item) => {
      const needsVerify = (item as any).needsVerification;
      const row = sheet.addRow({
        sn: globalItemNo++,
        desc: item.description,
        unit: item.unit,
        qty: item.quantity,
        rate: item.rate || '',
        amount: item.amount || '',
      });
      row.getCell('qty').numFmt = '#,##0.00';
      row.getCell('rate').numFmt = '#,##0.00';
      row.getCell('amount').numFmt = '#,##0.00';
      row.getCell('qty').font = { bold: true };

      if (needsVerify) {
        row.fill = { type: "pattern", pattern: "solid", fgColor: { argb: VERIFY_BG } };
        row.getCell('desc').value = `⚠ ${item.description} [VERIFY]`;
      }
    });

    // Section subtotal
    const subtotalRow = sheet.addRow({
      desc: `${section.sectionName} — Subtotal`,
      amount: section.subtotal,
    });
    subtotalRow.font = { bold: true, size: 10 };
    subtotalRow.fill = { type: "pattern", pattern: "solid", fgColor: { argb: SUBTOTAL_BG } };
    subtotalRow.getCell('amount').numFmt = '#,##0.00';
    grandTotal += section.subtotal;

    sheet.addRow({}); // spacer
  });

  // Grand total + VAT
  sheet.addRow({});
  const gtRow = sheet.addRow({ desc: "Grand Total (excl. VAT)", amount: grandTotal });
  gtRow.font = { bold: true, size: 12 };
  gtRow.getCell('amount').numFmt = '#,##0.00';

  const vatRow = sheet.addRow({ desc: "VAT (5%)", amount: grandTotal * 0.05 });
  vatRow.font = { bold: true, size: 11 };
  vatRow.getCell('amount').numFmt = '#,##0.00';

  const totalRow = sheet.addRow({ desc: "Total (incl. VAT)", amount: grandTotal * 1.05 });
  totalRow.font = { bold: true, size: 13, color: { argb: BRAND_COLOR } };
  totalRow.getCell('amount').numFmt = '#,##0.00';
  totalRow.fill = { type: "pattern", pattern: "solid", fgColor: { argb: SECTION_BG } };

  // Footer
  sheet.addRow({});
  const footerRow = sheet.addRow(["Generated by QS-HUB V15 — www.qshub.ae"]);
  footerRow.font = { size: 8, italic: true, color: { argb: "999999" } };
  sheet.mergeCells(footerRow.number, 1, footerRow.number, 6);

  const safeName = data.projectName.replace(/[<>:"/\\|?*\s]+/g, "_");
  const revSuffix = data.revision ? `_Rev${data.revision}` : '';

  // ── Audit Trail Sheet ──
  if (data.auditData) {
    const auditSheet = workbook.addWorksheet("Audit Trail", { properties: { defaultColWidth: 20 } });
    const auditHeader = auditSheet.addRow(["Discipline", "Category", "Key / Scope", "Area (m²)", "Perimeter (LM)", "Width (m)", "Height (m)", "Volume (m³)"]);
    auditHeader.font = { bold: true, color: { argb: HEADER_FONT_COLOR } };
    auditHeader.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "333333" } };
    
    // Add rooms
    const safeRooms = Array.isArray(data.auditData.rawOutputs?.strQuantities?.rooms) ? data.auditData.rawOutputs.strQuantities.rooms : [];
    safeRooms.forEach((r: any) => {
      auditSheet.addRow([
        "Spatial", "Room/Space", `${r.scope || ''} - ${r.key || ''}`, 
        r.areaM2 ? Number(r.areaM2).toFixed(2) : "", 
        r.perimeterM ? Number(r.perimeterM).toFixed(2) : "",
        r.widthM ? Number(r.widthM).toFixed(2) : "",
        r.heightM ? Number(r.heightM).toFixed(2) : "",
        ""
      ]);
    });
    
    // Add layers
    const layers = Array.isArray(data.auditData.rawOutputs?.layers) ? data.auditData.rawOutputs.layers : [];
    layers.forEach((l: any) => {
      auditSheet.addRow([
        "CAD Layer", "Pattern", l.layer || l.name || '', 
        l.area ? Number(l.area).toFixed(2) : "", 
        l.length ? Number(l.length).toFixed(2) : "",
        "", "",
        l.volume ? Number(l.volume).toFixed(2) : ""
      ]);
    });
  }

  const fileName = `V15_BOQ_${safeName}${revSuffix}_${Date.now()}.xlsx`;

  try {
    await mkdir(data.outputDir, { recursive: true });
    const filePath = path.join(data.outputDir, fileName);
    await workbook.xlsx.writeFile(filePath);
    return filePath;
  } catch (error) {
     throw new Error(
       `Failed to write Excel file: ${error instanceof Error ? error.message : String(error)}`,
       { cause: error }
     );
  }
}
